In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
 'trip_id': ['T001','T002','T003','T004','T005','T006','T007','T008','T009','T010'],
 'mode': ['Taxi','Bus','Bike','Taxi','Bus','Taxi','Bike','Bus','Taxi','Taxi'],
 'distance_km': [8.4,6.1,3.2,2.7,14.3,5.1,4.0,9.8,32.0,-1.5],
 'fare_cad': [19.5,3.75,0,11.2,3.75,13.2,0,3.75,72.0,15.0],
 'wait_min': [6,9,4,12,18,np.nan,3,11,55,8],
 'rating': [4,3,5,2,2,4,5,np.nan,1,3],
 'peak': ['No','Yes','No','Yes','Yes','No','No','Yes','Yes','Yes']
}

df = pd.DataFrame(data)

In [4]:
# one-hot encoding for nominal categories, using Pandas
df_encoded = pd.get_dummies(df, columns=['mode'], dtype=int)

df_encoded

,trip_id,distance_km,fare_cad,wait_min,rating,peak,mode_Bike,mode_Bus,mode_Taxi
0,T001,8.4,19.50,6.0,4.0,No,0,0,1
1,T002,6.1,3.75,9.0,3.0,Yes,0,1,0
2,T003,3.2,0.00,4.0,5.0,No,1,0,0
3,T004,2.7,11.20,12.0,2.0,Yes,0,0,1
4,T005,14.3,3.75,18.0,2.0,Yes,0,1,0
5,T006,5.1,13.20,NaN,4.0,No,0,0,1
6,T007,4.0,0.00,3.0,5.0,No,1,0,0
7,T008,9.8,3.75,11.0,NaN,Yes,0,1,0
8,T009,32.0,72.00,55.0,1.0,Yes,0,0,1
9,T010,-1.5,15.00,8.0,3.0,Yes,0,0,1

In [9]:
# ordinal categorize the fare_level

levels = ['Low','Medium','High']


df['fare_level'] = pd.cut(
    df['fare_cad'],
    bins=[-np.inf, 5, 15, np.inf],
    labels=levels
)

In [ ]:
# (alternatively) , using lambda expression

df['fare_level'] = df['fare_cad'].apply(
    lambda x: 'Low' if x <= 5
    else 'Medium' if x <= 15
    else 'High'
)

In [10]:
# ordinal encoding for ordinal categories, using Pandas

df['fare_encoded'] = df['fare_level'].cat.codes

In [11]:
df

,trip_id,mode,distance_km,fare_cad,wait_min,rating,peak,fare_level,fare_encoded
0,T001,Taxi,8.4,19.50,6.0,4.0,No,High,2
1,T002,Bus,6.1,3.75,9.0,3.0,Yes,Low,0
2,T003,Bike,3.2,0.00,4.0,5.0,No,Low,0
3,T004,Taxi,2.7,11.20,12.0,2.0,Yes,Medium,1
4,T005,Bus,14.3,3.75,18.0,2.0,Yes,Low,0
5,T006,Taxi,5.1,13.20,NaN,4.0,No,Medium,1
6,T007,Bike,4.0,0.00,3.0,5.0,No,Low,0
7,T008,Bus,9.8,3.75,11.0,NaN,Yes,Low,0
8,T009,Taxi,32.0,72.00,55.0,1.0,Yes,High,2
9,T010,Taxi,-1.5,15.00,8.0,3.0,Yes,Medium,1

# using scikit-learn for nominal and ordinal encoding

In [30]:
df = pd.DataFrame(data)

In [22]:
df

  trip_id  mode  distance_km  fare_cad  wait_min  rating peak
0    T001  Taxi          8.4     19.50       6.0     4.0   No
1    T002   Bus          6.1      3.75       9.0     3.0  Yes
2    T003  Bike          3.2      0.00       4.0     5.0   No
3    T004  Taxi          2.7     11.20      12.0     2.0  Yes
4    T005   Bus         14.3      3.75      18.0     2.0  Yes
5    T006  Taxi          5.1     13.20       NaN     4.0   No
6    T007  Bike          4.0      0.00       3.0     5.0   No
7    T008   Bus          9.8      3.75      11.0     NaN  Yes
8    T009  Taxi         32.0     72.00      55.0     1.0  Yes
9    T010  Taxi         -1.5     15.00       8.0     3.0  Yes

In [23]:
# for nominal encoding (one-hot)

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

onehot = OneHotEncoder(sparse_output=False, dtype=int)
onehot.set_output(transform='pandas')

encoded_df = onehot.fit_transform(df[['mode']])

df = pd.concat([df, encoded_df], axis=1)

display(df)

OneHotEncoder(dtype=<class 'int'>, sparse_output=False)

,trip_id,mode,distance_km,fare_cad,wait_min,rating,peak,mode_Bike,mode_Bus,mode_Taxi
0,T001,Taxi,8.4,19.50,6.0,4.0,No,0,0,1
1,T002,Bus,6.1,3.75,9.0,3.0,Yes,0,1,0
2,T003,Bike,3.2,0.00,4.0,5.0,No,1,0,0
3,T004,Taxi,2.7,11.20,12.0,2.0,Yes,0,0,1
4,T005,Bus,14.3,3.75,18.0,2.0,Yes,0,1,0
5,T006,Taxi,5.1,13.20,NaN,4.0,No,0,0,1
6,T007,Bike,4.0,0.00,3.0,5.0,No,1,0,0
7,T008,Bus,9.8,3.75,11.0,NaN,Yes,0,1,0
8,T009,Taxi,32.0,72.00,55.0,1.0,Yes,0,0,1
9,T010,Taxi,-1.5,15.00,8.0,3.0,Yes,0,0,1

In [19]:
encoded

# ['Bike', 'Bus', 'Taxi']

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [17]:
df

  trip_id  mode  distance_km  fare_cad  wait_min  rating peak
0    T001  Taxi          8.4     19.50       6.0     4.0   No
1    T002   Bus          6.1      3.75       9.0     3.0  Yes
2    T003  Bike          3.2      0.00       4.0     5.0   No
3    T004  Taxi          2.7     11.20      12.0     2.0  Yes
4    T005   Bus         14.3      3.75      18.0     2.0  Yes
5    T006  Taxi          5.1     13.20       NaN     4.0   No
6    T007  Bike          4.0      0.00       3.0     5.0   No
7    T008   Bus          9.8      3.75      11.0     NaN  Yes
8    T009  Taxi         32.0     72.00      55.0     1.0  Yes
9    T010  Taxi         -1.5     15.00       8.0     3.0  Yes

In [27]:
df

,trip_id,mode,distance_km,fare_cad,wait_min,rating,peak,mode_Bike,mode_Bus,mode_Taxi
0,T001,Taxi,8.4,19.50,6.0,4.0,No,0,0,1
1,T002,Bus,6.1,3.75,9.0,3.0,Yes,0,1,0
2,T003,Bike,3.2,0.00,4.0,5.0,No,1,0,0
3,T004,Taxi,2.7,11.20,12.0,2.0,Yes,0,0,1
4,T005,Bus,14.3,3.75,18.0,2.0,Yes,0,1,0
5,T006,Taxi,5.1,13.20,NaN,4.0,No,0,0,1
6,T007,Bike,4.0,0.00,3.0,5.0,No,1,0,0
7,T008,Bus,9.8,3.75,11.0,NaN,Yes,0,1,0
8,T009,Taxi,32.0,72.00,55.0,1.0,Yes,0,0,1
9,T010,Taxi,-1.5,15.00,8.0,3.0,Yes,0,0,1

In [24]:
# embedding, normally for Deep Learning enconding

In [32]:
import pandas as pd
import torch
import torch.nn as nn

# Step 1: Convert mode categories to integer indices
mode_ids, categories = pd.factorize(df['mode'])

# Step 2: Create an embedding layer
embedding = nn.Embedding(
    num_embeddings=len(categories),
    embedding_dim=5
)

# Step 3: Generate embeddings for all rows
indices = torch.tensor(mode_ids, dtype=torch.long)

with torch.no_grad():
    vectors = embedding(indices).numpy()

# Step 4: Add embeddings to the original DataFrame
# df[['mode_emb_1', 'mode_emb_2']] = vectors

vectors
# display(df)

array([[ 0.4559291 ,  1.2000113 ,  0.51091075, -0.91513306, -0.310797  ],
       [-1.3168561 , -0.68883413, -0.07359483,  0.98769754,  0.01082604],
       [-1.3169116 ,  0.5220172 , -0.79136306,  1.4610325 ,  0.5185248 ],
       [ 0.4559291 ,  1.2000113 ,  0.51091075, -0.91513306, -0.310797  ],
       [-1.3168561 , -0.68883413, -0.07359483,  0.98769754,  0.01082604],
       [ 0.4559291 ,  1.2000113 ,  0.51091075, -0.91513306, -0.310797  ],
       [-1.3169116 ,  0.5220172 , -0.79136306,  1.4610325 ,  0.5185248 ],
       [-1.3168561 , -0.68883413, -0.07359483,  0.98769754,  0.01082604],
       [ 0.4559291 ,  1.2000113 ,  0.51091075, -0.91513306, -0.310797  ],
       [ 0.4559291 ,  1.2000113 ,  0.51091075, -0.91513306, -0.310797  ]],
      dtype=float32)

Note: The embedding is randomly initialized and does not learn the actual relationships between Taxi, Bus, and Bike. 
Only by placing the embedding layer into a neural network and training it can meaningful vector representations be learned.