In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd

In [17]:
df = pd.read_csv('trip_sample.csv')

In [18]:
df.columns

Index(['trip_id', 'mode', 'distance_km', 'fare_cad', 'wait_min', 'rating',
       'peak'],
      dtype='object')

In [19]:
# First-pass inspection: learn the shape before the story

df.shape
df.columns
df.head()
df.tail()
df.info()
df.dtypes

# quick missing-value count
df.isna().sum()

# unique values in a category
df['mode'].value_counts(dropna=False)

(6, 7)

Index(['trip_id', 'mode', 'distance_km', 'fare_cad', 'wait_min', 'rating',
       'peak'],
      dtype='object')

  trip_id  mode  distance_km  fare_cad  wait_min  rating peak
0    T001  Bike          3.2      0.00       4.0       5  Yes
1    T002  Taxi          8.4     19.50       6.0       4   No
2    T003   Bus          6.1      3.75       9.0       3  Yes
3    T004  Taxi          2.7     11.20      12.0       2  Yes
4    T005   Bus         14.3      3.75      18.0       2  Yes

  trip_id  mode  distance_km  fare_cad  wait_min  rating peak
1    T002  Taxi          8.4     19.50       6.0       4   No
2    T003   Bus          6.1      3.75       9.0       3  Yes
3    T004  Taxi          2.7     11.20      12.0       2  Yes
4    T005   Bus         14.3      3.75      18.0       2  Yes
5    T006  Taxi          5.1     13.20       NaN       4   No

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   trip_id      6 non-null      object
 1   mode         6 non-null      object
 2   distance_km  6 non-null      float64
 3   fare_cad     6 non-null      float64
 4   wait_min     5 non-null      float64
 5   rating       6 non-null      int64
 6   peak         6 non-null      object
dtypes: float64(3), int64(1), object(3)
memory usage: 468.0+ bytes

trip_id         object
mode            object
distance_km    float64
fare_cad       float64
wait_min       float64
rating           int64
peak            object
dtype: object

trip_id        0
mode           0
distance_km    0
fare_cad       0
wait_min       1
rating         0
peak           0
dtype: int64

mode
Taxi    3
Bus     2
Bike    1
Name: count, dtype: int64

# Data Aggregation (GROUP BY)

In [30]:
df.groupby("mode")["wait_min"].agg(
    n="count",
    avg_wait="mean"
).reset_index()

   mode  n  avg_wait
0  Bike  1       4.0
1   Bus  2      13.5
2  Taxi  2       9.0

In [27]:
summary = (
    df.groupby('mode')['wait_min']
      .agg(['count', 'mean', 'median', 'min', 'max'])
      .sort_values('mean', ascending=False)
)

In [33]:
summary

      count  mean  median  min   max
mode
Bus       2  13.5    13.5  9.0  18.0
Taxi      2   9.0     9.0  6.0  12.0
Bike      1   4.0     4.0  4.0   4.0

In [32]:
summary.reset_index()

   mode  count  mean  median  min   max
0   Bus      2  13.5    13.5  9.0  18.0
1  Taxi      2   9.0     9.0  6.0  12.0
2  Bike      1   4.0     4.0  4.0   4.0

# Pivot tables and crosstabs: summarize categories

In [34]:
pd.crosstab(
    df['mode'],
    df['peak'],
    normalize='index'
)

peak        No       Yes
mode
Bike  0.000000  1.000000
Bus   0.000000  1.000000
Taxi  0.666667  0.333333